name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # runs-on: self-hosted
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}
      
    - name: Publish
      run: dotnet publish --framework net5.0 --configuration Release --self-contained -r win10-x64


    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebApp1
        path: D:\a\GitHub-CICD-Test\GitHub-CICD-Test\cfapp99\bin\Release\net5.0\win10-x64\publish\

    - name: Do this
      run: echo "Build number is ${env:BUILD_NUMBER}"
      
  deploy_local:
    needs: build
    runs-on: self-hosted
 
    steps: 
    - name: Prepare local folders
      run: |
        Remove-Item 'c:\pub\cfapp99_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\cfapp99_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\cfapp99 cfapp99_bak
        md c:\pub\cfapp99

    - name: Download new binaries to the local app
      uses: actions/download-artifact@v2
      with:
        name: WebApp1
        path: c:\pub\cfapp99

  deploy_remote:
    needs: deploy_local
    runs-on: self-hosted
 
    steps: 
    - name: Prepare remote folders
      run: |
        Remove-Item '\\WIN2019DC03\c$\pub\cfapp99_bak1' -Recurse -ErrorAction Ignore
        Remove-Item '\\WIN2019DC03\c$\pub\cfapp99_bak' -Recurse -ErrorAction Ignore
        ren \\WIN2019DC03\c$\pub\cfapp99 cfapp99_bak
        md \\WIN2019DC03\c$\pub\cfapp99

    - name: Copy from local folder to the production web app
      run: ROBOCOPY 'c:\pub\cfapp99' '\\WIN2019DC03\c$\pub\cfapp99' /mir /nfl

